/**
 * songLoader.js — the ONLY data access layer for songs.
 *
 * Songs come from a virtual module generated by the Vite content plugin
 * (see frontend/plugins/contentPlugin.js), which discovers the real files
 * in the root `Song Lyrics/` folder at dev/build time. Add a file there,
 * restart Vite, and it appears here automatically — no manual index.
 *
 * Components must only use the helpers in this module (never the virtual
 * import directly). When the Django backend lands, this file becomes the
 * seam: swap the virtual-module import for GET /api/songs/ and the UI
 * keeps working unchanged.
 */

import { songs, songCategories } from 'virtual:content:songs';

/** All songs, in stable discovery order. */
export function getSongs() {
  return songs;
}

/** All unique categories, in display order. */
export function getCategories() {
  return songCategories;
}

/** Find a single song by its slug. */
export function getSongBySlug(slug) {
  return songs.find((song) => song.slug === slug) ?? null;
}

function flattenLyrics(sections = []) {
  return sections.flatMap((section) => [
    section.label,
    section.labelEn,
    section.labelTa,
    ...(section.lines || []),
  ]);
}

/**
 * Filter + search the library. `query` matches titles, category, and the
 * lyrics themselves (both languages); `category` filters to one category.
 */
export function filterSongs({ query = '', category = 'All' }) {
  const q = query.trim().toLowerCase();
  return songs.filter((song) => {
    const matchesCategory = category === 'All' || song.category === category;
    if (!matchesCategory) return false;
    if (!q) return true;
    const haystack = [
      song.titleEn,
      song.titleTa,
      song.category,
      ...flattenLyrics(song.lyricsEn),
      ...flattenLyrics(song.lyricsTa),
    ];
    return haystack.some((value) => String(value ?? '').toLowerCase().includes(q));
  });
}

/* ------------------------------------------------------------------
   Language-aware accessors. The real content is Tamil-only today, so
   English falls back to Tamil instead of showing empty boxes.
------------------------------------------------------------------ */

/** Title in the active language (falls back to whichever exists). */
export function getSongTitle(song, lang) {
  const title = lang === 'ta' ? song.titleTa : song.titleEn;
  return title || song.titleEn || song.titleTa || '';
}

/** Sections in the active language (falls back to the Tamil lyrics). */
export function getSongLyrics(song, lang) {
  const sections = lang === 'ta' ? song.lyricsTa : song.lyricsEn;
  if (sections && sections.length) return sections;
  if (song.lyricsTa && song.lyricsTa.length) return song.lyricsTa;
  return [];
}
