/**
 * videoLoader.js — the ONLY data access layer for videos.
 *
 * Videos come from a virtual module generated by the Vite content plugin
 * (see frontend/plugins/contentPlugin.js), which discovers the real files
 * in the root `Video/` folder at dev/build time. Series folders become
 * series; files are never hardcoded here.
 *
 * Components must only use the helpers in this module (never the virtual
 * import directly). When the Django backend lands, this file becomes the
 * seam: swap the virtual-module import for GET /api/videos/ and the UI
 * keeps working unchanged.
 */

import { videos, videoCategories } from 'virtual:content:videos';

/** All videos, in stable discovery order (standalone first, then series). */
export function getVideos() {
  return videos;
}

/** All unique categories (series names + 'General'), in display order. */
export function getCategories() {
  return videoCategories;
}

/** Find a single video by its slug. */
export function getVideoBySlug(slug) {
  return videos.find((video) => video.slug === slug) ?? null;
}

/** The featured video (used on the home page preview). */
export function getLatestVideo() {
  return videos[0] ?? null;
}

/**
 * Filter + search across all available metadata: titles, series, episode,
 * category, description and the source file name.
 */
export function filterVideos({ query = '', category = 'All' }) {
  const q = query.trim().toLowerCase();
  return videos.filter((video) => {
    const matchesCategory = category === 'All' || video.category === category;
    if (!matchesCategory) return false;
    if (!q) return true;
    const haystack = [
      video.titleEn,
      video.titleTa,
      video.series,
      video.seriesEn,
      video.seriesTa,
      video.episode,
      video.episodeEn,
      video.episodeTa,
      video.category,
      video.descriptionEn,
      video.descriptionTa,
      video.fileName,
    ];
    return haystack.some((value) => String(value ?? '').toLowerCase().includes(q));
  });
}

/**
 * Related videos for a detail page — same series first, then same category,
 * never including the current video. Max `limit` results.
 */
export function getRelatedVideos(slug, limit = 3) {
  const current = videos.find((video) => video.slug === slug);
  if (!current) return [];
  const sameSeries = videos.filter(
    (video) => video.slug !== slug && video.series && video.series === current.series,
  );
  const sameCategory = videos.filter(
    (video) => video.slug !== slug && !sameSeries.includes(video) && video.category === current.category,
  );
  const others = videos.filter(
    (video) => video.slug !== slug && !sameSeries.includes(video) && !sameCategory.includes(video),
  );
  return [...sameSeries, ...sameCategory, ...others].slice(0, limit);
}

/* ------------------------------------------------------------------
   Language-aware accessors (local content is often Tamil-only, so these
   always fall back to whatever text exists).
------------------------------------------------------------------ */

export function getVideoTitle(video, lang) {
  const title = lang === 'ta' ? video.titleTa : video.titleEn;
  return title || video.titleEn || video.titleTa || '';
}

export function getSeriesLabel(video, lang) {
  if (!video.series) return '';
  return lang === 'ta' ? video.seriesTa || video.seriesEn : video.seriesEn || video.seriesTa;
}

export function getEpisodeLabel(video, lang) {
  if (!video.episode) return '';
  return lang === 'ta' ? video.episodeTa || video.episodeEn : video.episodeEn || video.episodeTa;
}

export function getVideoDescription(video, lang) {
  const description = lang === 'ta' ? video.descriptionTa : video.descriptionEn;
  return description || video.descriptionEn || video.descriptionTa || '';
}

/** MIME type for a local video source URL (by extension). */
export function getVideoMime(source) {
  const ext = String(source).split('?')[0].split('.').pop().toLowerCase();
  const map = {
    mp4: 'video/mp4',
    webm: 'video/webm',
    mov: 'video/quicktime',
    ogg: 'video/ogg',
    ogv: 'video/ogg',
    m4v: 'video/mp4',
    '3gp': 'video/3gpp',
  };
  return map[ext] || 'video/mp4';
}

/* ------------------------------------------------------------------
   YouTube URL builders — the only place YouTube URL formats live.
------------------------------------------------------------------ */

/** Standard thumbnail served by YouTube (no local downloads needed). */
export function getYouTubeThumbnail(youtubeId) {
  return `https://img.youtube.com/vi/${youtubeId}/hqdefault.jpg`;
}

/** Embed URL used by the responsive <iframe> player. */
export function getYouTubeEmbedUrl(youtubeId) {
  return `https://www.youtube.com/embed/${youtubeId}`;
}

/** "Watch on YouTube" link — opens the video's own page in a new tab. */
export function getYouTubeWatchUrl(youtubeId) {
  return `https://www.youtube.com/watch?v=${youtubeId}`;
}
