/**
 * contentPlugin.js — Vite plugin that makes the real content folders the
 * source of truth for the website.
 *
 * Songs live OUTSIDE the Vite root (project root → `Song Lyrics/`), so
 * they cannot be read with import.meta.glob. Instead the plugin reads the
 * folder in Node at dev/build startup and exposes the normalized data to
 * React as a virtual module:
 *
 *   virtual:content:songs   → { songs, songCategories }
 *
 * "Add a song file → restart/build Vite → it appears" works automatically —
 * nothing is manually maintained.
 *
 * Videos no longer live in a content folder: they are hand-maintained in
 * `src/data/videos.json` (id, title, type, parts[] with YouTube ids) and
 * imported directly by `src/content/videos/videoLoader.js`.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSong } from '../src/content/songs/songParser.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FRONTEND_DIR = path.resolve(__dirname, '..');
const PROJECT_ROOT = path.resolve(FRONTEND_DIR, '..');
const SONGS_DIR = path.join(PROJECT_ROOT, 'Song Lyrics');

const VIRTUAL_SONGS = 'virtual:content:songs';

/* ------------------------------------------------------------------
   Song discovery
------------------------------------------------------------------ */

let cachedSongs = null;

function readSongs() {
  let files = [];
  try {
    files = fs
      .readdirSync(SONGS_DIR)
      .filter((name) => /\.txt$/i.test(name))
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  } catch (error) {
    console.warn(`[content-plugin] Could not read "${SONGS_DIR}": ${error.message}`);
    return [];
  }

  const songs = [];
  files.forEach((fileName, index) => {
    try {
      const text = fs.readFileSync(path.join(SONGS_DIR, fileName), 'utf8');
      const song = parseSong(text, {
        fileName,
        index,
        relPath: path.join('Song Lyrics', fileName).split(path.sep).join('/'),
      });
      songs.push(song);
    } catch (error) {
      // Never let one bad file take down the whole site.
      console.warn(
        `[content-plugin] Could not parse song "${fileName}" — skipped (${error.message})`,
      );
    }
  });
  return songs;
}

function loadSongs() {
  if (!cachedSongs) cachedSongs = readSongs();
  return cachedSongs;
}

function uniqueCategories(songs) {
  const seen = [];
  for (const song of songs) {
    if (!seen.includes(song.category)) seen.push(song.category);
  }
  return seen;
}

/* ------------------------------------------------------------------
   Plugin
------------------------------------------------------------------ */

export default function contentPlugin() {
  return {
    name: 'kiristhuvin-sabai-content',

    resolveId(id) {
      if (id === VIRTUAL_SONGS) return `\0${id}`;
      return null;
    },

    load(id) {
      if (id === `\0${VIRTUAL_SONGS}`) {
        const songs = loadSongs();
        return [
          '// Generated by contentPlugin.js — do not edit.',
          `export const songs = ${JSON.stringify(songs)};`,
          `export const songCategories = ${JSON.stringify(uniqueCategories(songs))};`,
        ].join('\n');
      }
      return null;
    },
  };
}
